---
apiVersion: v1
kind: Service
metadata:
  name: web-server-headers
spec:
  type: ClusterIP
  ports:
  - name: web
    targetPort: 5000
    port: 5000
  selector:
    app: web-server-headers
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-server-headers
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/upstream-vhost: "web-server-headers.default.svc.cluster.local"
spec:
  rules:
  - host: headers.t.cn
    http:
      paths:
      - backend:
          serviceName: web-server-headers
          servicePort: 5000
        path: /
